name: Build packages

on: 
  pull_request:
    paths:
      - 'client/src/**'
      - 'client/angular.json'
      - 'client/package.json'
      - 'client/tsconfig*'
      - 'server/**'
      - '!server/package-lock.json'

jobs:
  client-build:
    name: Build client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: |
          npm run build -- --prod

  server-build:
    name: Build Node Api package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
        
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci
        
      - name: Build packages
        run: |
          npm run build
