name: Build Angular packages

on: 
  pull_request:
    paths:
      - 'cms/core/**'
      - 'cms/modules/**'
      - 'cms/portal/**'
      - 'cms/cms-demo/**'
      - 'angular.json'
      - 'package.json'
      - 'tsconfig*'

jobs:
  cms-build:
    name: Build Angular packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cms

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: |
          npm run build:libs
          npm run build -- --prod
