name: Deploy

on: 
  push:
    branches:
      - 'deploy/**'
env:
    NODE_VERSION: "12.x"

jobs:
  cms-deploy:
    if: "!contains(github.event.head_commit.message, 'skip client')"
    name: Deploy Client To Github Page
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: |
          npm run build -- --prod

      - name: Deploy packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy -- --no-silent --cname=starter.typijs.com

  api-deploy:
    if: "!contains(github.event.head_commit.message, 'skip server')"
    name: Deploy Server To Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
            app-name: typijs
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: '.'