name: Create git release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  git-release:
    name: Create git release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate notes
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@master
        with:
          tag_name: ${{ github.ref }}
          changelog: CHANGELOG.md
      
      - name: Print changelog
        run: |
          echo "tag_name: ${{ github.ref }}"
          echo "changelog: ${{ join(fromJson(steps.generate_notes.outputs.notes).notes, '') }}"
        
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}
